### ISSUE TITLE
Poetry install not working

### ISSUE THREAD

**Issue by Arifi** [iridia-ulb/AI-book#2]
Salut, un peut d'aide SVP, j'arrive pas a dépasser l'étape "poetry install", voila ce que j'ai comme réponse :

```
poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing pygame (2.0.3)

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel



  WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
  Using WINDOWS configuration...

  Making dir :prebuilt_downloads:
  Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.16-VC.zip 13d952c333f3c2ebe9b7bc0075b4ad2f784e7584
  Unzipping :prebuilt_downloads\SDL2-devel-2.0.16-VC.zip:
  Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
  Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
  Downloading... https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip 1436df41ebc47ac36e02ec9bda5699e80ff9bd27
  Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.0.15-VC.zip:
  Downloading... https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip 9097148f4529cf19f805ccd007618dec280f0ecc
  Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.0.4-VC.zip:
  Downloading... https://www.pygame.org/ftp/jpegsr9d.zip ed10aa2b5a0fcfe74f8a6f7611aeb346b06a1f99
  Unzipping :prebuilt_downloads\jpegsr9d.zip:
  Downloading... https://pygame.org/ftp/prebuilt-x64-pygame-1.9.2-20150922.zip 3a5af3427b3aa13a0aaf5c4cb08daaed341613ed
  Unzipping :prebuilt_downloads\prebuilt-x64-pygame-1.9.2-20150922.zip:
  copying into .\prebuilt-x64
  Path for SDL: prebuilt-x64\SDL2-2.0.16
  ...Library directory for SDL: prebuilt-x64/SDL2-2.0.16/lib/x64
  ...Include directory for SDL: prebuilt-x64/SDL2-2.0.16/include
  Path for FONT: prebuilt-x64\SDL2_ttf-2.0.15
  ...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64
  ...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/include
  Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
  ...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
  ...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
  Path for MIXER: prebuilt-x64\SDL2_mixer-2.0.4
  ...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64
  ...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/include
  Path for PORTMIDI: prebuilt-x64
  ...Library directory for PORTMIDI: prebuilt-x64/lib
  ...Include directory for PORTMIDI: prebuilt-x64/include
  DLL for SDL2: prebuilt-x64/SDL2-2.0.16/lib/x64/SDL2.dll
  DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/SDL2_ttf.dll
  DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
  DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64/SDL2_mixer.dll
  DLL for portmidi: prebuilt-x64/lib/portmidi.dll
  Path for FREETYPE not found.
  ...Found include dir but no library dir in prebuilt-x64.
  Path for PNG not found.
  ...Found include dir but no library dir in prebuilt-x64.
  Path for JPEG not found.
  ...Found include dir but no library dir in prebuilt-x64.
  DLL for freetype: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/libfreetype-6.dll

  ---
  For help with compilation see:
      https://www.pygame.org/wiki/CompileWindows
  To contribute to pygame development see:
      https://www.pygame.org/contribute.html
  ---

  Traceback (most recent call last):
    File "C:\Users\Mourad\AppData\Roaming\pypoetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\Mourad\AppData\Roaming\pypoetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Mourad\AppData\Roaming\pypoetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Mourad\AppData\Local\Temp\tmpc538x9rv\.venv\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Mourad\AppData\Local\Temp\tmpc538x9rv\.venv\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "C:\Users\Mourad\AppData\Local\Temp\tmpc538x9rv\.venv\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
    File "C:\Users\Mourad\AppData\Local\Temp\tmpc538x9rv\.venv\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 400, in <module>
    File "C:\Users\Mourad\AppData\Local\Temp\tmpe7l1m7im\pygame-2.0.3\buildconfig\config.py", line 241, in main
      deps = CFG.main(**kwds)
             ^^^^^^^^^^^^^^^^
    File "C:\Users\Mourad\AppData\Local\Temp\tmpe7l1m7im\pygame-2.0.3\buildconfig\config_win.py", line 574, in main
      return setup_prebuilt_sdl2(prebuilt_dir)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Mourad\AppData\Local\Temp\tmpe7l1m7im\pygame-2.0.3\buildconfig\config_win.py", line 499, in setup_prebuilt_sdl2
      DEPS.configure()
    File "C:\Users\Mourad\AppData\Local\Temp\tmpe7l1m7im\pygame-2.0.3\buildconfig\config_win.py", line 336, in configure
      from . import vstools
    File "C:\Users\Mourad\AppData\Local\Temp\tmpe7l1m7im\pygame-2.0.3\buildconfig\vstools.py", line 11, in <module>
      compiler.initialize()
    File "C:\Users\Mourad\AppData\Local\Temp\tmpc538x9rv\.venv\Lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 403, in initialize
      vc_env = query_vcvarsall(VERSION, plat_spec)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Mourad\AppData\Local\Temp\tmpc538x9rv\.venv\Lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 281, in query_vcvarsall
      raise DistutilsPlatformError("Unable to find vcvarsall.bat")
  distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat


  at ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\poetry\installation\chef.py:147 in _prepare
      143│
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│
      146│             if error is not None:
    → 147│                 raise error from None
      148│
      149│             return path
      150│
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pygame (2.0.3) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pygame (==2.0.3)"'.
```

**Comment by KenN7** [comment]
Bonjour,

Quelle est votre version de python ?

Pouvez vous lancer la commande suivante et copier le résultat ici ?
pip wheel --use-pep517 "pygame (==2.0.3)"

**Comment by Arifi** [comment]
Merci @KenN7 pour votre réponse, actuellement j'ai pu exécuter l'appli en changeant le fichier .toml comme suit:
```
python = ">3.10"
pygame = ">=2.5"
```
j'ai python 3.10.6 et un autre 3.11. Je vais essayer votre solution.

**Comment by Arifi** [comment]
@KenN7  J'ai downgrade a la version 2.0.3 et maintenant ça marche !
Je pense que c'est dus a l'installation d'un environnement sur VSCode hier
Merci quand-même :)

**Comment by Arifi** [comment]
@KenN7  J'ai downgrade a la version 2.0.3 et maintenant ça marche !
Je pense que c'est dus a l'installation d'un environnement sur VSCode hier
Merci quand-même :)

**Comment by KenN7** [comment]
Bonjour, votre modification du fichier toml était correcte, le problème vient de l'absence de ressources pré-compilés pour pygame et votre version de python. Donc une version de pygame plus récente est une bonne solution.
